package.json, server/config/filestorage.js, server/initializers/filestorage.js
Gpx files they are compressed on upload using gzip, images are downscaled to 1024 px on upload
=> compress gpx and downscale images

client/views/layout.html, i18n/bg.json
show nomenclatures and species menu items if user is admin
=> show nomenclatures and species menu items if admin

client/views/monitorings/birds.html, client/views/monitorings/cbm.html, client/views/monitorings/ciconia.html, client/views/monitorings/herptiles.html, client/views/monitorings/mammals.html
Make map larger in form detail pages
=> make the map larger in entry forms

server/actions/user.js, server/templates/register/html.ejs
send mail to the user after successful registration
=> send registration mail

server/helpers/Model.js, server/helpers/actions.js, server/models/formBirds.js, server/models/formCBM.js, server/models/formHerps.js, server/models/formHerptiles.js, server/models/formMammals.js
- add Observation date and time in UTC in the csv
- fix ciconia export
=> UTC time in exports and export fixes

client/scripts/controllers/ZonesController.js, client/views/dashboard.html, client/views/layout.html, client/views/zones/list.html, client/views/zones/view.html, server/actions/zoneOwnership.js, server/actions/zones.js
allow CBM moderator to access zones and visits
=> allow CBM moderator to access zones and visits

client/views/monitorings/list_birds.html, client/views/monitorings/list_cbm.html, client/views/monitorings/list_ciconia.html, client/views/monitorings/list_herptiles.html, client/views/monitorings/list_mammals.html
Date column in form lists now uses observationDate value.
=> fix date sorting in forms lists

client/scripts/directives/listMap.js
open records detail page when click on the map marker
=> open detail page on marker click

server/config/api.js, server/config/i18n.js, server/config/logger.js, server/config/sequelize.js, server/config/servers/web.js
Staging environment to allow separate configuration between production and staging
=> Configuration for staging environment

server/templates/export_ready/html.ejs, server/templates/lost_password/html.ejs, server/templates/register/html.ejs
=> Email templates are translated to en/bg and annotated

client/scripts/configs/states.js, client/scripts/controllers/MonitoringDetailController.js, client/scripts/directives/formDetailButtons.js, client/views/directives/formdetailbuttons.html, client/views/monitorings/birds.html, client/views/monitorings/cbm.html, client/views/monitorings/ciconia.html, client/views/monitorings/herptiles.html, client/views/monitorings/invertebrates.html, client/views/monitorings/list_birds.html, client/views/monitorings/list_cbm.html, client/views/monitorings/list_ciconia.html, client/views/monitorings/list_herptiles.html, client/views/monitorings/list_invertebrates.html, client/views/monitorings/list_mammals.html, client/views/monitorings/mammals.html, i18n/bg.json
Refactored form detail buttons to use directive and improved to show label only in -lg and have access keys
=> Allow navigating to previous/next record in form detail

client/scripts/controllers/MonitoringDetailController.js
Keep current coordinates in CBM record when changing the zone
=> keep coordinates when change zone in cbm record

README.md, client/views/home-birds.html, client/views/home-cbm.html, client/views/home-ciconia.html, client/views/home-herptiles.html, client/views/home-mammals.html, client/views/home.html
update copyright dates to 2015-2018
=> update copyright dates

client/scripts/controllers/MonitoringController.js, client/scripts/directives/exportButtons.js, client/scripts/filters/min.js, client/views/directives/exportbuttons.html, client/views/monitorings/list_birds.html, client/views/monitorings/list_cbm.html, client/views/monitorings/list_ciconia.html, client/views/monitorings/list_herptiles.html, client/views/monitorings/list_invertebrates.html, client/views/monitorings/list_mammals.html, i18n/bg.json, server/initializers/formMethods.js
- Limit export to 20000 records 
- Extract export buttons to separate directive
- Show also records to export count
=> limit export

server/actions/zoneOwnership.js, test/actions/zoneOwnership.js
allow CBM moderators to manage zone requests
=> allow CBM moderators to manage zone requests

server/actions/user.js, server/config/app.js, server/config/routes.js, server/initializers/forms.js, server/initializers/mailchimp.js, server/tasks/mailchimp.js, server/utils/capitalizeFirstLetter.js, test/actions/users.js, test/fixtures/02-users.js
User can be deleted only by administrator. When deleting user all his form data are migrated to a system user. Mailchimp removal task is initialized.
=> Delete user with adopting form data and mailchimp removal

client/scripts/configs/i18n.js
Fix language detection if passed as query param
=> Language detection

client/scripts/directives/totalRecordsStats.js, client/scripts/services/api.js, client/views/directives/totalRecordsStats.html, client/views/home.html, i18n/bg.json, server/migrations/20181128081159-create-total-records-stats-view.js, server/models/total_users_records_year.js, server/tasks/statistics.js
Show top observers stats in home page.
Records shown are sum of all records made by the user in all the forms.
=> Top observers stats

client/scripts/configs/states.js, client/scripts/controllers/MobileStatsController.js, client/scripts/directives/totalRecordsStats.js, client/views/directives/totalRecordsStats.html, client/views/home.html, client/views/mobile-stats.html, i18n/bg.json
Create a page for showing stats trough mobile app
=> mobile stats

client/scripts/controllers/StatsController.js
Open corresponding form from birds interesting species stats
=> Open correct form from stats

server/migrations/20181129081346-update-birds-stats-with-cbm-and-ciconia.js, server/models/birds_top_interesting_species_month.js
Include data from CBM and Ciconia forms in birds statistics
=> include cbm and ciconia data in top stats

server/models/birds_top_interesting_species_month.js, server/models/birds_top_species_month.js, server/models/herptiles_top_interesting_species_month.js, server/models/herptiles_top_species_month.js, server/models/invertebrates_top_interesting_species_month.js, server/models/invertebrates_top_species_month.js, server/models/mammals_top_interesting_species_month.js, server/models/mammals_top_species_month.js
Fix duplicate records in top species stats
=> fix issue with stats

client/scripts/controllers/StatsController.js, client/scripts/services/api.js, client/views/stats.html, server/migrations/20181203093540-create-user-ranking-view.js, server/models/user_rank_stats.js, server/tasks/statistics.js
Show user current position in private stats
=> Show user position in stats

client/scripts/controllers/MobileStatsController.js, client/views/mobile-stats.html
- Move plants form at the bottom of the list
- Make form titles bold
=> Mobile stats UI changes

client/scripts/directives/previewPictures.js, client/views/directives/previewpictures.html, client/views/monitorings/list_birds.html, client/views/monitorings/list_cbm.html, client/views/monitorings/list_ciconia.html, client/views/monitorings/list_herptiles.html, client/views/monitorings/list_invertebrates.html, client/views/monitorings/list_mammals.html, client/views/monitorings/list_plants.html, client/views/monitorings/list_public.html, server/actions/filestorage.js, server/forms/_common.js, server/helpers/filestorage.js, test/actions/filestorage.js, test/helpers/filestorage.js, test/publicforms.js
- Show images icon in public and private lists for records containing images
- Preview record images from public and private lists without opening details page
=> Preview images in lists

client/scripts/controllers/MonitoringDetailController.js, client/scripts/directives/field.js, client/views/monitorings/geolocation.html, server/forms/_common.js, server/migrations/20190603135952-add-geolocation-accuracy.js
Add geolocationAccuracy field in all forms
=> Add geolocationAccuracy field in common model

client/scripts/controllers/MonitoringDetailController.js, client/scripts/directives/field.js, client/scripts/services/geolocation.js, client/views/monitorings/geolocation.html
This helps GPS to achieve a fix and provide position with better accuracy
=> Request continuous location

client/views/monitorings/birds.html, client/views/monitorings/herptiles.html, i18n/bg.json, i18n/en.json
Similar to birds collapse of extra fields
=> Collapse extra herptiles fields

server/initializers/forms.js
Add custom hooks giving the ability for additional model data validation and modification.
New hooks are:
- beforeApiUpdate
- afterApiUpdate
=> Custom sequelize hooks

server/initializers/formMethods.js, test/publicforms.js
Support species field to be optional for the forms that has species
=> Optional species

client/scripts/directives/threatType.js, client/views/monitorings/list_threats.html
Display as primary and secondary type. In case of poison the poison type, in case of threat the threat type.
=> Display threat type

client/scripts/configs/forms.js, client/scripts/configs/states.js, client/views/monitorings/list_threats_public.html, server/forms/threats.js, test/publicforms.js
Displays threads type, species if available and count in public list
Includes #85
=> Display detailed data in threats public list

client/scripts/filters/capitalize.js
=> Add capitalize filter

client/scripts/configs/forms.js
Threats must be filterable by user
=> Allow filter by user

client/scripts/directives/listMap.js, client/views/directives/listmap.html, client/views/directives/listmapmarker.html, client/views/directives/mapmarkerthreats.html, client/views/monitorings/list_threats.html, client/views/monitorings/list_threats_public.html
Show threat primary type and category in map marker window
=> Show threat category on map

client/views/users/detail.html
Make language field required, because "select" field will support removing selected value(#90 )
=> Make language field in profile form required

client/views/users/detail.html
Make all select fields required since this field will support removing selected value(see #90 )
=> Make all select fields required

client/scripts/directives/field.js, client/views/fields/select.html
Refactor select field to look as single-choice and support removing selected value
=> Refactor select field

Procfile, package.json
Setup heroku
- Add Procfile with start command
- Add heroku-postbuild task for creating public form stats
=> Add heroku procfile and postbuild commant for generating stats

package.json
=> Remove filestorage dependency

package-lock.json, package.json
* not used
Seems it was a peer dependency of actionhero back in v14
=> Remove ws dependency

server/config/redis.js, server/config/sequelize.js, server/utils/urlParser.js, test/utils/urlParser.js
Create urlParser util and use it for parsing Redis and DB URLs
=> Fix parsing redis and DB URLs

server/forms/herptiles.js, server/forms/invertebrates.js, server/forms/mammals.js
Fix skipping fields in forms export
Closes #200
=> Skip export fields

server/initializers/filestorage.js
Fix uploading images caused by sharp dependency update.
Closes #198
=> Fix image uploading

server/migrations/20190826135230-insert-threats-and-findings-nomenclatures.js, server/migrations/20190903143318-create-threats-index.js
Fix migrations, broken after updating sequelize version.
=> Fix migrations

server/migrations/20200323070308-add-form-threats-stats-date.js, server/models/threats_stats.js
Adds observation timestamp to exported records so it is possible to filter on the frontend side.
=> Public threats filter

package-lock.json, package.json, server/initializers/formMethods.js, server/migrations/20190826135230-insert-threats-and-findings-nomenclatures.js, server/migrations/20190903143318-create-threats-index.js, server/tasks/mailchimp.js
- fix migrations
- only run mailchimp tasks if enabled
- fix filter by location
=> Release 1.0.3

server/models/location.js, server/models/nomenclature.js, server/models/organization.js, server/models/species.js, server/models/user.js, server/utils/languageField.js, server/utils/object.js, test/models/nomenclature.js, test/models/organization.js, test/models/species.js
A field that has a separate value for each supported language
=> Language field

.github/workflows/nodejs.yml
Need to verify tests are not broken
=> Create github workflow to build and test

server/initializers/formActions.js, server/initializers/forms.js, server/migrations/20200407172234-add-form-local-language.js, server/models/location.js, server/utils/languageField.js, server/utils/localField.js, test/actions/formBirds.js, test/actions/formCBM.js, test/actions/formCiconia.js, test/actions/formFilters.js, test/actions/formHerptiles.js, test/actions/formInvertebrates.js, test/actions/formMammals.js, test/actions/formThreats.js, test/forms.js, test/forms/plants.js
Instead of providing `local` field, a field with language code will be provided. This is backward compatible.
=> Restore api for forms

config/languages.js, server/forms/threats.js, server/initializers/forms.js, server/migrations/20200417084850-add-threats-stats-lang-fields.js, server/models/threats_stats.js, server/tasks/statistics.js, server/utils/localField.js
Restored stats format with language code suffix and generate based on data.
Used a hacky approach to inject poison type translations. Will think of something better in the future.
=> Fix threats public stats and hooks

server/actions/autocomplete.js, server/config/routes.js, server/forms/_extra.js, server/initializers/formActions.js, server/initializers/formMethods.js, server/initializers/forms.js, server/migrations/20200522121531-add-auto-location-local-indexes.js, server/migrations/20200611132845-add-stats-auto-location.js, server/models/birds_top_interesting_species_month.js, server/models/herptiles_top_interesting_species_month.js, server/models/invertebrates_top_interesting_species_month.js, server/models/mammals_top_interesting_species_month.js, server/models/plants_top_interesting_species_month.js, test/features/auto-location-filter.js
- Filter by auto location
- Autocomplete service over settlements
- Update stats to include auto location
=> Filter auto location

package.json, server/forms/_common.js, server/forms/_extra.js, server/forms/birds.js, server/forms/ciconia.js, server/forms/herptiles.js, server/forms/invertebrates.js, server/forms/mammals.js, server/forms/plants.js, server/forms/threats.js, server/initializers/formActions.js, server/initializers/formMethods.js, server/migrations/20200614045738-add-forms-moderator-review.js, test/forms/contextCount.js, test/forms/moderatorReview.js
New boolean field `moderatorReview` and additional `context=count` to return only counts on listing.
=> Moderator review

server/forms/_common.js, server/forms/birds.js, server/forms/cbm.js, server/forms/ciconia.js, server/forms/herptiles.js, server/forms/invertebrates.js, server/forms/mammals.js
Update unique hash fields to better distinguish similar but different records.
=> Add fields for form hash calculation

package-lock.json, package.json, server/tasks/autoLocation.js
Bounding the search within the allowed max distance
=> Optimize autoLocation task

.github/workflows/nodejs.yml, .travis.yml, __tests__/test-pg.js, __utils__/jest-environment-ah/index.js, __utils__/jest-environment-ah/package.json, __utils__/setupPg.js, docker-compose.yml, jest.pg.config.js, package-lock.json, package.json, server/config/sequelize.js, server/initializers/sequelize.js, test/_setup.js, test/actions/zoneOwnership.js, test/actions/zones.js, test/fixtures/01-nomenclatures.js, test/fixtures/01-species.js, test/fixtures/04-zones.js, test/fixtures/05-formCBM.js
Tests running against postgresql to validate more completely the db integration
=> PostgreSQL tests

__tests__/actions/bgatlas2008.js, __tests__/models/user.js, __utils__/factories/userFactory.js, server/actions/bgatlas2008.js, server/config/routes.js, server/migrations/20200804153630-create-bgatlas2008-user-selected.js, server/models/user.js, test/_setup.js
Allow user to set and retrieve selected cells through two new apis:
GET /bgatlas2008/user/selected
POST /bgatlas2008/user/selected
=> feat(bgatlas): user selected cells

__tests__/actions/bgatlas2008.js, server/actions/bgatlas2008.js, server/config/routes.js, server/models/bgatlas2008_stats_user.js
Provide statistics about total observed and known species as well as top 3 observers.
Closes #500
=> feat(bgatlas): endpoint for cell statistics

__tests__/actions/bgatlas2008.js, server/actions/bgatlas2008.js, server/models/bgatlas2008_observed_species.js
Include `others` flag in cell info - true when anyone have observed the species.
=> feat(bgatlas): add others observation to cell info

config/languages.js, server/config/banner.js, server/migrations/20210126153725-add-el-tr-ar-fr-languages.js, tools/user_banner_ar.sh, tools/user_banner_el.sh, tools/user_banner_fr.sh, tools/user_banner_tr.sh
Add greece (el), turkish (tr), arabic (ar) and french (fr) languages
=> feat(i18n): add el, tr, ar and fr languages

server/initializers/formActions.js, server/initializers/formMethods.js, test/permissions.js
Friends should only be allowed to see records, not modify or delete them.
=> feat(forms): forbid friends to modify/delete records

.github/workflows/codeql-analysis.yml
Fails on master so updated to latest example
=> feat(lint): update codeql workflow with latest example

package-lock.json, package.json
Reverts BspbOrg/smartbirds-server#752
production is still on node 10
=> Revert "build(deps-dev): bump husky from 6.0.0 to 7.0.2"

config/crontab, scripts/.env, scripts/run_task, scripts/start, scripts/stop, scripts/update, scripts/update_cron
Scripts for starting/stopping and updating on unmanaged environment
Based on the idea that separate user account is created for the service and it's `~/.bashrc` contains the necessary environment configuration
=> Operational scripts

__tests__/actions/forms/fields/birdsNewSpeciesModeratorReview.js, server/forms/_fields/newSpeciesModeratorReview.js
is not reconsidered for moderator review
=> fix: moderator confirm of first record in utm grid

server/initializers/session.js
set plain user data in session instead of sequelize model
=> fix(session): set plain user data in session instead of sequelize model

server/config/logger.js
=> chore(logs): add job name in logs

package-lock.json, package.json
Reverts BspbOrg/smartbirds-server#1141
=> Revert "build(deps-dev): bump @commitlint/config-conventional from 17.6.6 to 19.2.2"

package-lock.json, package.json
Reverts BspbOrg/smartbirds-server#1129
=> Revert "build(deps-dev): bump @commitlint/cli from 17.7.1 to 19.3.0"

Dockerfile
=> build(docker): remove volumes since they are defined in compose

server/initializers/formMethods.js
Increase query limit for admin users to 50000
=> feat(export): increase query limit for admins

__tests__/__snapshots__/db-schema.js.snap, server/forms/herptiles.js, server/migrations/20250402075334-alter-herptiles-add-traps-count.js
Add trapsCount field to FormHerptiles
=> feat(form-herptiles): add trapsCount field
