BspbOrg/smartbirds-server

client/scripts/configs/i18n.js, client/styles/custom.less, client/views/home.html, public/index.html
On home page the logo is changed with interpolation, while on form pages the logo is applied with css, so a global `lang-XX` is added to `html` and appropriate overrides for the logo.
=> Use new logo of Bspb and localize

server/config/i18n.js
Actually we don't use it and it is a recipe for mistake by accidentally committing the file
=> Don't update localization files from server

client/scripts/services/trackService.js, server/initializers/filestorage.js
This is wrong as the length is actually of the compressed content
=> Don't send content length for gzipped streams

server/actions/user.js, server/initializers/mailchimp.js, server/tasks/mailchimp.js
When user is created it is scheduled for creation in mailchimp. The old update task is removed and new one is created that uses [update member](http://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#edit-put_lists_list_id_members_subscriber_hash) and batch operation to update the list. Tested with 400 users simultaneously.
=> Refactor mailchimp integration

client/styles/custom.less
Fix stats background in birds public page
Before:
After:
=> fix public birds page background

client/scripts/controllers/MonitoringController.js, client/scripts/directives/monitoringList.js, client/views/directives/monitoring_list.html, client/views/monitorings/list_birds.html, client/views/monitorings/list_cbm.html, client/views/monitorings/list_ciconia.html, client/views/monitorings/list_herptiles.html, client/views/monitorings/list_invertebrates.html, client/views/monitorings/list_mammals.html, client/views/monitorings/list_plants.html, client/views/monitorings/list_public.html, i18n/bg.json, i18n/en.json
In form lists instead of infinitely retrying to fetch next page, displays an error message and retry button.
* [bg message](https://poeditor.com/projects/po_edit?order=&filter=&id=146255&id_language=24&search=NO_CONNECTION_WITH_SERVER)
* [en message](https://poeditor.com/projects/po_edit?order=&filter=&id=146255&id_language=43&search=NO_CONNECTION_WITH_SERVER)
To simulate - login to [staging](http://smartbirds-staging.herokuapp.com/), disable connection, open a form
=> Handle no server connection in lists and allow retry

client/scripts/controllers/MonitoringDetailController.js, client/scripts/directives/field.js, client/views/fields/geolocation.html, client/views/monitorings/birds.html, client/views/monitorings/cbm.html, client/views/monitorings/ciconia.html, client/views/monitorings/geolocation.html, client/views/monitorings/herptiles.html, client/views/monitorings/invertebrates.html, client/views/monitorings/mammals.html, client/views/monitorings/plants.html, i18n/bg.json, i18n/en.json
Latitude and longitude fields have button to fill with current location. If user have already granted permission to access location, on new record it is populated with current location.
As a side effect both fields share common term `DETAIL_LATITUDE` and `DETAIL_LONGITUDE`. The old `${FORM}_DETAIL_LATITUDE` and `${FORM}_DETAIL_LONGITUDE` are no longer used.
To test - login to [staging](https://smartbirds-staging.herokuapp.com/) and start new form record.
=> Fill form geolocation with current location

client/scripts/controllers/MonitoringDetailController.js
When creating new record the observation date and time are prefilled with current time and date. If necessary user can still change them.
=> Fill observationDateTime with current timestamp on new record

client/views/directives/monitoring_list.html, client/views/directives/topStats.html, client/views/directives/totalRecordsStats.html, client/views/mobile-stats.html, client/views/nomenclatures/list.html, client/views/species/list.html, client/views/stats.html, client/views/users/list.html, client/views/visits/list.html
Instead of overflowing the screen on mobile, the tables are horizontally scrollable
See bootstrap [docs](https://getbootstrap.com/docs/3.3/css/#tables-responsive)
=> Make all tables responsive

client/styles/main.less, client/views/monitorings/birds.html, client/views/monitorings/cbm.html, client/views/monitorings/ciconia.html, client/views/monitorings/herptiles.html, client/views/monitorings/invertebrates.html, client/views/monitorings/mammals.html, client/views/monitorings/plants.html
Instead of a set of button on top and bottom of form, the buttons are sticky and always visible
=> Sticky mobile actions

client/scripts/directives/configLabel.js
In case the value is not set instead of crashing it's better to render empty string.
Also added validation that configuration has label.
=> Support empty value in config-label

client/scripts/directives/field.js, client/scripts/services/db.js
Refactor db service to index nomenclatures with EN labels instead BG. 
EN label and nomenclature type will be used as identifier in the future
=> Use nomenclatures EN label as key in db service

server/forms/threats.js, server/initializers/forms.js
Uses the existing export, and adds the additional fields by resolving the primary type and poison type.
TODO: use i18n files to get localized labels for poison category type.
Pending validation from @GPopgeorgiev for the format.
=> Include fields for balkan threats db in export

server/migrations/20200122114937-add-organization-relation.js
A migration tries to drop default on a column, but that fails in sqlite. In this particular case it's safe to skip it.
=> Fix migration on tests

server/initializers/sequelize.js
A migration error was masked and did not actually result in error.
=> Properly handle failed auto migrations

server/models/user.js
With the addition of international users it's better to have the english as default.
=> Set english as default language for newly created users

.gitignore, server/forms/_common.js, server/forms/cbm.js, server/initializers/formActions.js, server/initializers/formMethods.js, server/initializers/forms.js, server/migrations/20200420123303-add-forms-organization-field.js, test/actions/organizations.js, test/fixtures/02-users.js
Organization is automatically populated on creation with the user's current organization. On record update the initial organization is kept unchanged (as requested).
=> Add organization to every form record and allow filtering by it

server/initializers/forms.js
Fixes threats export when first record doesn't have species, the fields are not defined in header and later on not exported.
=> Always include species fields in export

__utils__/factories/formCommonFactory.js
The code is only used in tests and doesn't make sense to use the slower but crypto secure random.
=> lint: silence lgtm insecure randomness warning

__tests__/actions/session.js, __tests__/models/user.js, server/actions/session.js, server/models/user.js
Similar to login `include: ['bgatlasCells']` list parameter
will include in the `response.user.bgatlasCells`
the selected cells with their coordinates
=> feat(bgatlas): user selected bg atlas cells in auth restore

__tests__/tasks/statistics.js, server/tasks/statistics.js, server/utils/capitalizeFirstLetter.js
Export global atlas cell stats for use in public pages.
Exported stats is `bgatlas2008_global_stats.json`
=> feat(bgatlas): export atlas global stats

__tests__/actions/bgatlas2008.js, server/actions/bgatlas2008.js, server/config/routes.js, server/models/bgatlas2008_observed_user_species.js, test/_setup.js
A new endpoint `/bgatlas/cell/:utm_code` that returns a list of `[{ species: String, known: Boolean, observed: Boolean}]` where:
* `known` is true if species is observed in bgatlas2008 for that cell
* `observed` is true if user have observed the species in that cell
closes #496
=> feat(bgatlas): return cell info for user

__tests__/actions/bgatlas2008.js, server/actions/bgatlas2008.js, server/config/routes.js, server/migrations/20201128083630-create-view-bgatlas2008-stats-user-rank.js, server/models/bgatlas2008_stats_user_rank.js
Always includes the requester user even if not within top 10 users.
Example:
```json
{
"count": 450,
"data": [
{ "count": 234, "position": 1, "user": { "id": 1, "firstName": "First", "lastName": "User" } },
{ "//": "... skip for brevity" },
{ "count": 14, "position": 23, "user": { "id": 222, "firstName": "Current", "lastName": "User" } }
]
}
```
=> feat(bgatlas): user rank stats api

server/initializers/forms.js
allow setting null value for multiple choice input when updating form
=> fix(form): set null to multiple choice

__tests__/__snapshots__/db-schema.js.snap, __tests__/db-schema.js, server/forms/ciconia.js
Properly export approximateDateStorksAppeared and approximateDateDisappearanceWhiteStorks fields as dates instead of timestamps.
=> fix(ciconia): properly export FormCiconia approximateDate fields
